In [1]:
import pandas as pd
import numpy as np
import config
from sqlalchemy import text
print(config.version)
print(config.connection_string)
pd.set_option('display.max_columns', None)

3.2.25.Dev
postgresql://postgres:sa@localhost/icip

In [2]:
sql = """select * from apl.damir_age_stats 
where (psp_spe_snds > 0 and psp_spe_snds <= 42)
or (psp_act_snds > 0 and psp_act_snds <= 50)
"""
damir = pd.read_sql(sql, config.connection_string)
damir
damir["psp_act_snds"].unique()

array([nan, 19., 21., 24., 26., 27., 28., 29., 30., 50.])

In [3]:
sql =f"""
    select year, sum(pop) pop, sum(pop0002)/sum(pop) p0002, sum(pop0305)/sum(pop) p0305, sum(pop0610)/sum(pop) p0610, sum(pop1117)/sum(pop) p1117, sum(pop1824)/sum(pop) p1824, sum(pop2539)/sum(pop) p2539, sum(pop4054)/sum(pop) p4054, sum(pop5564)/sum(pop) p5564, sum(pop6579)/sum(pop) p6579, sum(pop80p)/sum(pop) p80p
    from iris.pop_iris
    group by year
"""
pop_iris = pd.read_sql(sql, config.connection_string)
pop_iris

,year,pop,p0002,p0305,p0610,p1117,p1824,p2539,p4054,p5564,p6579,p80p
0,17,66524339.0,0.033483,0.036020,0.062297,0.086886,0.080529,0.181509,0.199545,0.125545,0.133869,0.060316
1,18,66732538.0,0.032751,0.035499,0.062088,0.087010,0.080370,0.180906,0.197685,0.125763,0.137137,0.060790
2,19,66988403.0,0.032675,0.035360,0.061754,0.086514,0.080379,0.181087,0.197473,0.126082,0.137625,0.061051
3,20,67162154.0,0.032056,0.034700,0.061375,0.086881,0.080607,0.180414,0.195735,0.126311,0.140958,0.060963
4,21,67408052.0,0.031403,0.033951,0.060709,0.087117,0.081043,0.179629,0.194405,0.126668,0.144234,0.060842
5,22,67760573.0,0.030695,0.033124,0.059789,0.087089,0.081350,0.179274,0.193287,0.126985,0.147673,0.060733

In [4]:
pop_iris[pop_iris["year"]==20].iloc[0].to_dict()

{'year': 20.0,
 'pop': 67162153.99999993,
 'p0002': 0.03205633570254441,
 'p0305': 0.03469965383959883,
 'p0610': 0.06137455685564376,
 'p1117': 0.0868814920527383,
 'p1824': 0.08060697124120436,
 'p2539': 0.18041440053576832,
 'p4054': 0.19573528970808624,
 'p5564': 0.12631058481640933,
 'p6579': 0.14095808265358642,
 'p80p': 0.0609626325944209}

In [5]:
def compute_overrepresentation(damir_dataset, year, psp_spe_snds, psp_act_snds):
    yy=min(year,22)  # MAJ in 26 for 22
    is_medecin = psp_spe_snds is not None
    props=pop_iris[pop_iris["year"]==yy].iloc[0].to_dict()
    bb = 1 if psp_spe_snds==1 or psp_spe_snds==12 else 0
    damir = damir_dataset[damir_dataset["ann"]==year]
    if is_medecin:
        damir = damir[damir["psp_spe_snds"]==psp_spe_snds]
    else:
        damir = damir[damir["psp_act_snds"]==psp_act_snds]
    overs={"year":year, "psp_spe_snds":psp_spe_snds, "psp_act_snds":psp_act_snds}
    overs["p0002"]=(damir[damir["age_ben_snds"]==0]["ratio"]*(3+bb*3)/20/(props["p0002"])).iloc[0]
    overs["p0305"]=(damir[damir["age_ben_snds"]==0]["ratio"]*3/20/(props["p0305"])).iloc[0]
    overs["p0610"]=(damir[damir["age_ben_snds"]==0]["ratio"]*(5-bb)/20/(props["p0610"])).iloc[0]
    overs["p1117"]=(damir[damir["age_ben_snds"]==0]["ratio"]*(7-bb)/20/(props["p1117"])).iloc[0]
    overs["p1824"]=((damir[damir["age_ben_snds"]==0]["ratio"]*(2-bb)/20+damir[damir["age_ben_snds"]==20]["ratio"].iloc[0]*5/10)/(props["p1824"])).iloc[0]
    overs["p2539"]=((damir[damir["age_ben_snds"]==20]["ratio"]*5/10+damir[damir["age_ben_snds"]==30]["ratio"].iloc[0]*10/10)/(props["p2539"])).iloc[0]
    overs["p4054"]=((damir[damir["age_ben_snds"]==40]["ratio"]*10/10+damir[damir["age_ben_snds"]==50]["ratio"].iloc[0]*5/10)/(props["p4054"])).iloc[0]
    overs["p5564"]=((damir[damir["age_ben_snds"]==50]["ratio"]*5/10+damir[damir["age_ben_snds"]==60]["ratio"].iloc[0]*5/10)/(props["p5564"])).iloc[0]
    overs["p6579"]=((damir[damir["age_ben_snds"]==60]["ratio"]*5/10+damir[damir["age_ben_snds"]==70]["ratio"].iloc[0]*10/10)/(props["p6579"])).iloc[0]
    ratio99 = damir[damir["age_ben_snds"]==99]["ratio"].iloc[0] if len(damir[damir["age_ben_snds"]==99]) > 0 else 0
    overs["p80p"]=((damir[damir["age_ben_snds"]==80]["ratio"]*10/10+ratio99*10/10)/(props["p80p"])).iloc[0]
    if psp_spe_snds == 12:
        # overs["p0002"]+=overs["p1117"]
        # overs["p0002"]+=overs["p1824"]
        # overs["p0002"]+=overs["p2539"]
        # overs["p0002"]+=overs["p4054"]
        # overs["p0002"]+=overs["p5564"]
        # overs["p0002"]+=overs["p6579"]
        # overs["p0002"]+=overs["p80p"]
        # overs["p1117"]=overs["p1824"]=overs["p2539"]=overs["p4054"]=overs["p5564"]=overs["p6579"]=overs["p80p"]=0
        overs["p1824"]=overs["p2539"]=overs["p4054"]=overs["p5564"]=overs["p6579"]=overs["p80p"]=0
    elif psp_spe_snds == 34:
        overs["p0002"]=overs["p0305"]=overs["p0610"]=overs["p1117"]=overs["p1824"]=overs["p2539"]=overs["p4054"]=overs["p5564"]=0
    return overs

overs = compute_overrepresentation(damir, 20, 12, None)
overs

{'year': 20,
 'psp_spe_snds': 12,
 'psp_act_snds': None,
 'p0002': 8.478881926391882,
 'p0305': 3.916492750490749,
 'p0610': 2.9523839556071763,
 'p1117': 3.1284210134152275,
 'p1824': 0,
 'p2539': 0,
 'p4054': 0,
 'p5564': 0,
 'p6579': 0,
 'p80p': 0}

In [6]:
def df_append_dict(df, dico):
    dico_df = pd.DataFrame([dico])
    return pd.concat([df, dico_df], ignore_index=True)

df = pd.DataFrame(columns=overs.keys())
df = df_append_dict(df, overs)
df

,year,psp_spe_snds,psp_act_snds,p0002,p0305,p0610,p1117,p1824,p2539,p4054,p5564,p6579,p80p
0,20,12,None,8.478882,3.916493,2.952384,3.128421,0,0,0,0,0,0

In [7]:
years=damir["ann"].unique()
print(years)
psp_spe_sndss=damir["psp_spe_snds"].dropna().unique()
psp_act_sndss=damir["psp_act_snds"].dropna().unique()
print(psp_spe_sndss)
psp_act_sndss

[20 21 22 23 24 25]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 11. 12. 13. 14. 15. 18. 31. 32. 33.
 34. 35. 36. 37. 38. 42.]

array([19., 21., 24., 26., 27., 28., 29., 30., 50.])

In [8]:
df = pd.DataFrame(columns=overs.keys())
for year in years:
    for i in psp_spe_sndss:
        overs = compute_overrepresentation(damir, year, i, None)
        df = df_append_dict(df, overs)
    for i in psp_act_sndss:
        overs = compute_overrepresentation(damir, year, None, i)
        df = df_append_dict(df, overs)
df

,year,psp_spe_snds,psp_act_snds,p0002,p0305,p0610,p1117,p1824,p2539,p4054,p5564,p6579,p80p
0,20,1.0,NaN,0.429115,0.198213,0.149420,0.158329,0.302018,0.488332,0.797484,1.204417,2.000359,4.641092
1,20,2.0,NaN,0.238745,0.220558,0.207830,0.205540,0.505889,0.766123,1.002764,1.417306,2.064290,1.784820
2,20,3.0,NaN,0.031924,0.029492,0.027790,0.027484,0.085264,0.167130,0.624233,1.435033,2.938378,3.927019
3,20,4.0,NaN,0.183206,0.169249,0.159482,0.157726,0.520381,0.743630,1.160038,1.552325,1.953714,1.596876
4,20,5.0,NaN,0.610961,0.564420,0.531848,0.525989,0.904416,0.958070,0.914742,1.067732,1.533263,1.740601
...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,25,NaN,27.0,0.597979,0.554129,0.511653,0.491773,0.639631,0.721860,0.807550,1.053179,1.760367,2.612077
194,25,NaN,28.0,3.573308,3.311279,3.057458,2.938663,0.985013,0.110424,0.156783,0.312896,0.646211,1.259833
195,25,NaN,29.0,1.453465,1.346883,1.243640,1.195319,1.226102,1.192096,0.640906,1.096081,0.954589,0.244170
196,25,NaN,30.0,0.149731,0.138752,0.128116,0.123138,0.659530,0.950275,1.160743,1.498517,1.243465,2.472110
197,25,NaN,50.0,0.096955,0.089845,0.082958,0.079735,0.231090,0.314364,0.412220,1.088392,3.130611,3.733309

In [9]:
df.to_sql("overrepresentation_2", config.connection_string, schema="apl", if_exists="replace", index=False)

198

In [10]:
sql = """
select o.psp_spe_snds, o.p0002-o2.p0002 p0002, o.p80p-o2.p80p p80p from apl.overrepresentation_2 o2
join apl.overrepresentation o on o.year=o2.year and o.psp_spe_snds = o2.psp_spe_snds
where o.p0002 != o2.p0002 or o.p80p != o2.p80p
and o.year=20
order by o.p0002-o2.p0002 desc
"""
diff = pd.read_sql(sql, config.connection_string)
diff.head(20)

    psp_spe_snds     p0002      p80p
0           12.0  3.325872  0.000000
1           12.0  3.259811  0.000000
2           12.0  3.107292  0.000000
3           12.0  3.088535  0.000000
4           12.0  3.045366  0.000000
5            1.0  0.482755 -1.794945
6            1.0  0.476271 -1.858657
7            1.0  0.457910 -1.748881
8            1.0  0.444444 -1.708402
9            1.0  0.439792 -1.766723
10          33.0  0.269837  0.396024
11          33.0  0.266390  0.395915
12          33.0  0.262749  0.407628
13          33.0  0.262207  0.402918
14          33.0  0.247146  0.432470
15          15.0  0.190633 -0.554673
16          15.0  0.189560 -0.541074
17          31.0  0.188547 -0.031847
18          15.0  0.187341 -0.552678
19          15.0  0.185874 -0.550218