In [1]:
import pandas as pd
import numpy as np
import config
import datetime
import sys
from sqlalchemy import text
print(sys.version)
print(config.version)
print(config.connection_string)
pd.set_option('display.max_columns', None)

3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]
3.2.25.Dev
postgresql://postgres:sa@localhost/icip

In [2]:
specialite=21
year=24
dico={}
year, specialite

(24, 21)

In [3]:
spe = pd.read_sql("select * from specialite", config.connection_string)
spe

,id,label,label_long,psp_spe_snds,psp_act_snds,doctolib
0,2,Anest,Anesthésiste,2.0,NaN,None
1,10,Generaliste,Généraliste,1.0,NaN,None
2,11,Cardio,Cardiologue,3.0,NaN,None
3,12,Chirugien,Chirugien,4.0,NaN,None
4,13,Endocrino,Endocrinologue,42.0,NaN,None
5,4,Gastro,Gastro-entérologue,8.0,NaN,None
6,5,Gyneco,Gynécologue,7.0,NaN,None
7,15,Neuro,Neurologue,32.0,NaN,None
8,6,Opthtalmo,Opthtalmogue,15.0,NaN,None
9,16,ORL,Oto-rhino-laryngologiste,11.0,NaN,None
10,17,Pneumo,Pneumologue,13.0,NaN,None
11,1,Psychiatre,Psychiatre,33.0,NaN,None
12,8,Radio,Radiologue,6.0,NaN,None
13,18,Radiotherapeuthe,Radiothérapeuthe,NaN,NaN,None
14,19,Rhumato,Rhumatologue,14.0,NaN,None
15,20,Stomato,Stomatologue,18.0,NaN,None
16,14,Geriatre,Gériatre,34.0,NaN,None
17,21,Infirmier,Infirmier,NaN,24.0,None
18,22,Sage-femme,Sage-femme,NaN,21.0,None
19,23,Kine,Masseur-Kinésithérapeute,NaN,26.0,None
20,24,Podologue,Pédicure-podologue,NaN,27.0,None
21,25,Orthophoniste,Orthophoniste,NaN,28.0,None
22,26,Pharmacie,Pharmacie,NaN,50.0,None
23,27,Dentiste,Chirurgien-dentaire,NaN,19.0,None
24,9,Dentiste2,Dentiste,36.0,NaN,None
25,28,Psychologue,Psychologue,NaN,NaN,None
26,3,Dermato,Dermatologue,5.0,NaN,dermatologue
27,7,Pediatre,Pédiatre,12.0,NaN,pediatre

In [4]:
def get_ps(year, specialite):
    sql=f"""
select sp.specialite_id, s.label_long as label, ds.annee as year, ps.id as p_id, an.lon, an.lat from ps
join tarif t on t.ps_id = ps.id
join tarif_date_source tds on tds.tarif_id=t.id
join date_source ds on ds.id=tds.date_source_id
join cabinet c on t.cabinet_id=c.id
join adresse_raw ar on c.adresse_raw_id=ar.id
join adresse_norm an on ar.adresse_norm_id=an.id
join specialite_profession sp on sp.profession_id=t.profession_id
join specialite s on s.id=sp.specialite_id
where sp.specialite_id={specialite}
and ds.annee={year}
"""
    print(f"Quering PS for year {year} and specialite {specialite}")
    return pd.read_sql(sql, config.connection_string).dropna()

In [5]:
def get_pa(year, specialite, is_medecin=True):
    if is_medecin:
        sql=f"""
select sp.specialite_id, s.label_long as label, ds.annee as year, pa.id as p_id, an.lon, an.lat
from apl.ps_libreacces ps
join personne_activite pa on pa.inpp=ps.inpp
join pa_adresse_norm_date_source pands on pands.personne_activite_id=pa.id and pands.date_source_id=ps.date_source_id
join personne_activite_diplome pad on pad.personne_activite_id=pa.id
join diplome d on d.code_diplome=ps.code_diplome
join profession_diplome pd on pd.diplome_id=d.id
join profession p on p.id=pd.profession_id
join specialite_profession sp on sp.profession_id=p.id
join specialite s on s.id=sp.specialite_id
join adresse_norm an on an.id=pands.adresse_norm_id
join date_source ds on ds.id=pands.date_source_id
where sp.specialite_id={specialite}
and ps.code_mode_exercice='L'
and ds.annee={year}
and pands.adresse_norm_id is not null
"""
    else:
        sql=f"""
select sp.specialite_id, s.label_long as label, ds.annee as year, pa.id as p_id, an.lon, an.lat
from apl.ps_libreacces ps
join personne_activite pa on pa.inpp=ps.inpp
join pa_adresse_norm_date_source pands on pands.personne_activite_id=pa.id and pands.date_source_id=ps.date_source_id
join profession_code_profession pcp on pcp.code_profession_id=ps.code_profession
join specialite_profession sp on sp.profession_id=pcp.profession_id
join specialite s on s.id=sp.specialite_id
join adresse_norm an on an.id=pands.adresse_norm_id
join date_source ds on ds.id=pands.date_source_id
where sp.specialite_id={specialite}
and ps.code_mode_exercice='L'
and ds.annee={year}
and ps.cp is not null
"""   
    print(f"Quering PA for year {year} and specialite {specialite} and is_medecin {is_medecin}")
    # print(sql)
    return pd.read_sql(sql, config.connection_string)

In [6]:
def get_rpps(year, specialite):
    sql=f"""
select personne.id p_id,an.lon,an.lat from personne
join diplome_obtenu dio on dio.personne_id = personne.id
join diplome d on d.id=dio.diplome_id
join profession_diplome pd on pd.diplome_id=d.id
join profession p on pd.profession_id=p.id
join specialite_profession sp on sp.profession_id=p.id
join coord c on c.personne_id=personne.id
join adresse_norm an on c.adresse_norm_id=an.id
where sp.specialite_id={specialite}
and personne.date_maj >= '20{year}-01-01' and date_effet <= '20{year}-12-31'
"""
    print(f"Quering RPPS for year {year} and specialite {specialite}")
    return pd.read_sql(sql, config.connection_string).dropna()

In [7]:
df2=get_pa(23,21, False)
# df2["p_id"].nunique()
len(df2)

Quering PA for year 23 and specialite 21 and is_medecin False

0

In [8]:
nb_unique = len(df2.groupby(["p_id", "lon", "lat"]))
nb_unique

0

In [9]:
nb = df2["p_id"].nunique()
nb

0

In [10]:
sql = f"select * from ameli where year=20{year}"
ameli_df = pd.read_sql(sql, config.connection_string)
ameli_df

    year  specialite  nb_metro  nb_dom_tom
0   2024           1      6230          78
1   2024           2      3839          60
2   2024           3      2386          48
3   2024           4      1980          40
4   2024           5       648          16
5   2024           6      4188          99
6   2024           7      2628          82
7   2024           8      6562         124
8   2024          10     50111        1664
9   2024          11      4916         102
10  2024          12       921          18
11  2024          13       825          28
12  2024          14       119           7
13  2024          15      1050          22
14  2024          16      1921          35
15  2024          17      1197          26
16  2024          18       460          10
17  2024          19      1408          24
18  2024          20       684          12
19  2024          21     94033        4595
20  2024          22      7807         383
21  2024          23     78627        3474
22  2024          24     12810         215
23  2024          25     21049         714
24  2024          27     35737        1143

In [11]:
ameli = {}
for _, row in ameli_df.iterrows():
    ameli[row["specialite"]]=row["nb_metro"]
ameli

{1: 6230,
 2: 3839,
 3: 2386,
 4: 1980,
 5: 648,
 6: 4188,
 7: 2628,
 8: 6562,
 10: 50111,
 11: 4916,
 12: 921,
 13: 825,
 14: 119,
 15: 1050,
 16: 1921,
 17: 1197,
 18: 460,
 19: 1408,
 20: 684,
 21: 94033,
 22: 7807,
 23: 78627,
 24: 12810,
 25: 21049,
 27: 35737}

In [13]:
columns=["specialite","label","year","ameli","nb_ps_cabinet","nb_ps","delta_ps","nb_pa_cabinet","nb_pa","delta_pa"]
df = pd.DataFrame(columns=columns)
for specialite in range(1,28):
    for yy in range(20,27): 
        ps_df=get_ps(yy,specialite)
        nb_unique_ps=len(ps_df.groupby(["p_id", "lon", "lat"]))
        nb_ps=ps_df["p_id"].nunique()
        pa_df=get_pa(yy,specialite,specialite<=20)
        label=pa_df["label"][0] if len(pa_df["label"])>0 else ""
        nb_unique_pa=len(pa_df.groupby(["p_id", "lon", "lat"]))
        nb_pa=pa_df["p_id"].nunique()
        # rpps_df=get_rpps(yy,specialite)
        # nb_unique_rpps=len(rpps_df.groupby(["p_id", "lon", "lat"]))
        # nb_rpps=rpps_df["p_id"].nunique()
        a=np.nan
        if yy==year and specialite in ameli:
            a=ameli[specialite]
            print(f"Found Ameli for specialite {specialite}: {a}")
        df=pd.concat([pd.DataFrame([[specialite,label,yy,a,nb_unique_ps,nb_ps,(nb_ps-a)/a,nb_unique_pa,nb_pa,(nb_pa-a)/a]], columns=df.columns), df], ignore_index=True)
df=df.sort_values(by=['specialite',"year"])
df

Quering PS for year 20 and specialite 1
Quering PA for year 20 and specialite 1 and is_medecin True
Quering PS for year 21 and specialite 1
Quering PA for year 21 and specialite 1 and is_medecin True
Quering PS for year 22 and specialite 1
Quering PA for year 22 and specialite 1 and is_medecin True
Quering PS for year 23 and specialite 1
Quering PA for year 23 and specialite 1 and is_medecin True
Quering PS for year 24 and specialite 1
Quering PA for year 24 and specialite 1 and is_medecin True
Found Ameli for specialite 1: 6230
Quering PS for year 25 and specialite 1
Quering PA for year 25 and specialite 1 and is_medecin True
Quering PS for year 26 and specialite 1
Quering PA for year 26 and specialite 1 and is_medecin True
Quering PS for year 20 and specialite 2

KeyboardInterrupt:

In [ ]:
df.to_excel("out/ps_stats.xlsx", index=False)
df.to_sql("ps_stats", config.connection_string, schema="apl", if_exists="replace", index=False)